### PR TITLE
Adding ability to split entry with keybinding

### PR DESCRIPTION
**Pull request by saccarosium**
Related to #8 

I'm quite happy with how it function now. 

I just needed to check if do we maintain the `...Split` variants of the command?

### CODE REVIEW

**Comment by bfrg** [comment]
Thanks for the PR. I'm not sure if I want to get rid of the old behavior. Maybe an option can be added where users can decide the behavior.

There's also a mapping missing for opening the selection in a new tab. Maybe `<C-t>`?

And I don't like polluting the global namespace `g:` with a variable just for the purpose of setting a temporary value that is used somewhere in the plugin.

 I need to think about it.

**Comment by saccarosium** [comment]
> And I don't like polluting the global namespace g: with a variable just for the purpose of setting a temporary value that is used somewhere in the plugin.

TBH I don't like it either. But I wanted to get your advise.

> There's also a mapping missing for opening the selection in a new tab. Maybe <C-t>?

Yes, I will include this.

> I'm not sure if I want to get rid of the old behavior.

This is only because it would be easier to remove it but I know you are using them

**Comment by bfrg** [comment]
It seems like `:FzyOldfiles` doesn't work anymore with this PR. And wouldn't it be convenient if users could specify the mappings for opening in a new split, vsplit or tab? What if someone wanted to use Alt instead of Ctrl?

**Comment by saccarosium** [comment]
I've re-did the changes. Now should work all well and be retro compatible with `...Split` commands.

Let me know if there is something else.

**Comment by saccarosium** [comment]
This should be ready for merging let me know if there is anything else.

**Comment by bfrg** [comment]
Why did you close it? Unfortunately, I've been quite busy the last few months. I am open to add this feature. I just noticed that I should refactor a few things which is why I haven't merged it immediately.

**Comment by saccarosium** [comment]
Hi, unfortunately I no longer use vim and I can't support this PR further if you have asked me further changes.

**Pull request closed without merging**
